# -*- coding: utf-8 -*-
"""translator-app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yHAw6RytCrjcZYjMoOpjoGojyEFp3ECJ

Downloades liber
"""

from transformers import MarianTokenizer, MarianMTModel
import gradio as gr

"""models will use in project"""

models = {
    "English → French": "Helsinki-NLP/opus-mt-en-fr",
    "French → English": "Helsinki-NLP/opus-mt-fr-en",
    "English → Arabic": "Helsinki-NLP/opus-mt-en-ar",
    "Arabic → English": "Helsinki-NLP/opus-mt-ar-en",
}

"""choose the model will use"""

loaded_models = {}
def load_model(direction):
    if direction not in loaded_models:
        model_name = models[direction]
        tokenizer = MarianTokenizer.from_pretrained(model_name)
        model = MarianMTModel.from_pretrained(model_name)
        loaded_models[direction] = (tokenizer, model)
    return loaded_models[direction]

"""transelate methode"""

def translate(text, direction):
    if not text.strip():
        return "⚠️ Please enter text to translate."
    tokenizer, model = load_model(direction)
    tokens = tokenizer(text, return_tensors="pt", padding=True, truncation=True)
    outputs = model.generate(**tokens)
    translation = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return translation

"""interface"""

interface = gr.Interface(
    fn=translate,
    inputs=[
        gr.Dropdown(
            choices=list(models.keys()),
            value="English → French",
            label="Select translation direction"
        ),
        gr.Textbox(label="Enter text"),
    ],
    outputs="text",
    title="Multilingual Translator 🌍",
    description="Translate text between English, French, and Arabic using MarianMT models.",
    theme="default"
)
interface.launch()

